In [39]:
import pandas as pd
import numpy as np
import struct
import numpy as np

import os
import pcapy as p
from scapy.all import *
import matplotlib.pyplot as plt

import pandas as pd

import struct
import numpy as np

import pcaps
# to play with the lib in real time
%load_ext autoreload
%autoreload 2

import glob 
import warnings
warnings.filterwarnings('ignore')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [49]:
data = "allumer_on_off_bw.pcapng"
for data in glob.glob('./*.pcapng'):#parquet
    df = pcaps.readPCAP_Doppler(data)
    pcaps.savePCAP(df,data)
df

,ID,t,TYPE,bReqType,bReq,wVal,wIndex,wLength,Payload,Length
1,2,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\x12\x01\x00\x02\x00\x00\x00@\xb4\x04\x0...,19.0
3,4,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\t\x02.\x00\x01\x01\x00\xa02\t\x04\x00\x...,47.0
5,6,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03',1.0
8,9,0.010,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xffhI{=\x19\x01A\x00t\x00\xad\x...,512.0
12,13,0.015,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xffhIa=*\x01\x12\x00]\x00\xd0\x...,512.0
...,...,...,...,...,...,...,...,...,...,...
9754,9755,10.740,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I%=\xe6\x000\xfe\xe0\xff...,512.0
9759,9760,10.745,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I$=\xe3\x00\x8a\xfe\xdf\...,512.0
9764,9765,10.750,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I\x0f=\xc9\x00\x10\xff\x...,512.0
9768,9769,10.755,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I\x1d=\xa6\x00\x89\xff\x...,512.0
9772,9773,10.760,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3IE=\x88\x00\xbf\xff\xcc\...,512.0

In [50]:
df

,ID,t,TYPE,bReqType,bReq,wVal,wIndex,wLength,Payload,Length
1,2,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\x12\x01\x00\x02\x00\x00\x00@\xb4\x04\x0...,19.0
3,4,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\t\x02.\x00\x01\x01\x00\xa02\t\x04\x00\x...,47.0
5,6,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03',1.0
8,9,0.010,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xffhI{=\x19\x01A\x00t\x00\xad\x...,512.0
12,13,0.015,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xffhIa=*\x01\x12\x00]\x00\xd0\x...,512.0
...,...,...,...,...,...,...,...,...,...,...
9754,9755,10.740,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I%=\xe6\x000\xfe\xe0\xff...,512.0
9759,9760,10.745,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I$=\xe3\x00\x8a\xfe\xdf\...,512.0
9764,9765,10.750,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I\x0f=\xc9\x00\x10\xff\x...,512.0
9768,9769,10.755,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3I\x1d=\xa6\x00\x89\xff\x...,512.0
9772,9773,10.760,DOPPLER,NaN,NaN,NaN,NaN,NaN,b'\x00\xff\x00\xff\xd3IE=\x88\x00\xbf\xff\xcc\...,512.0

In [51]:
data = "allumer_on_off_bw.pcapng" 
df = pd.read_parquet(data+".parquet")
df

,ID,t,TYPE,bReqType,bReq,wVal,wIndex,wLength,Payload,Length
1,2,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\x12\x01\x00\x02\x00\x00\x00@\xb4\x04\x0...,19.0
3,4,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\t\x02.\x00\x01\x01\x00\xa02',10.0
5,6,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\t\x02.\x00\x01\x01\x00\xa02\t\x04\x00\x...,47.0
7,8,0.000,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03\x02\x00',3.0
9,10,0.001,OTHER,NaN,NaN,NaN,NaN,NaN,b'\x03',1.0
...,...,...,...,...,...,...,...,...,...,...
17458,17460,52.246,OTHER,NaN,NaN,NaN,NaN,NaN,b'',0.0
17459,17462,52.247,OTHER,NaN,NaN,NaN,NaN,NaN,b'',0.0
17461,17464,52.247,OTHER,NaN,NaN,NaN,NaN,NaN,b'',0.0
17463,17466,52.247,OTHER,NaN,NaN,NaN,NaN,NaN,b'',0.0
17465,17468,52.247,OTHER,NaN,NaN,NaN,NaN,NaN,b'',0.0